services:
  github-client:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: github_client_app
    ports:
      - "8000:8000"
    env_file:
      - ../.env
    volumes:
      - ./private-key.pem:/docker/private-key.pem
    environment:
      - GITHUB_PRIVATE_KEY_PATH=/docker/private-key.pem