version: "3.9"

services:
  github-client:
    build: ./docker
    container_name: github_client_app
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./docker/private_key.pem:/app/private_key.pem