services:
  github-client:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: github_client_app
    ports:
      - "8000:8000"
    env_file:
      - ../.env
    volumes:
      - ./private_key.pem:/app/private_key.pem